name: Build macOS and Windows Apps v0.0

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller

    - name: Build macOS App with PyInstaller
      run: |
        pyinstaller --onefile --clean import_members.py

    - name: Sign macOS App
      run: |
        # Sign the app with ad-hoc signature
        codesign --force --deep --sign - dist/import_members

    - name: Upload macOS App artifact
      uses: actions/upload-artifact@v4
      with:
        name: import-members-app-mac
        path: dist/import_members

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller

    - name: Build Windows EXE with PyInstaller
      run: |
        # Create a clean build directory
        if (Test-Path "build") { Remove-Item -Recurse -Force "build" }
        if (Test-Path "dist") { Remove-Item -Recurse -Force "dist" }
        
        # Build with PyInstaller
        pyinstaller --onefile --clean --noconsole --name "import_members" `
          --hidden-import=pandas `
          --hidden-import=openpyxl `
          import_members.py

    - name: Test Windows EXE
      run: |
        # Create a test directory
        New-Item -ItemType Directory -Force -Path "test_run"
        Copy-Item "dist\import_members.exe" -Destination "test_run\"
        
        # Create a test file
        Set-Content -Path "test_run\Ironblood V.txt" -Value "{}"
        
        # Run the exe and capture output
        Set-Location "test_run"
        $output = & ".\import_members.exe" 2>&1
        Write-Output $output

    - name: Upload Windows EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: import-members-app-win
        path: dist/import_members.exe 