name: Build macOS and Windows Apps v0.0

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller

    - name: Build macOS App with PyInstaller
      run: |
        pyinstaller --onefile --clean import_members.py

    - name: Sign and notarize macOS App
      run: |
        # Create a self-signed certificate
        openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=Self Signed"
        
        # Create a p12 certificate
        openssl pkcs12 -export -out certificate.p12 -inkey key.pem -in cert.pem -password pass:password
        
        # Create a temporary keychain
        security create-keychain -p password build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p password build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
        
        # Import certificate
        security import certificate.p12 -k build.keychain -P password -T /usr/bin/codesign
        
        # Sign the app
        codesign --force --deep --sign "Self Signed" dist/import_members
        
        # Clean up
        security delete-keychain build.keychain
        rm key.pem cert.pem certificate.p12

    - name: Upload macOS App artifact
      uses: actions/upload-artifact@v4
      with:
        name: import-members-app-mac
        path: dist/import_members

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller

    - name: Build Windows EXE with PyInstaller
      run: |
        pyinstaller --onefile --clean --noconsole import_members.py

    - name: Upload Windows EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: import-members-app-win
        path: dist/import_members.exe 